; Conditional Library includes - only if the Library exists it will then be included
; Output: ~ScriptName_includes.ahk

; Call this function in the auto-execute section
; Include ~ScriptName_includes.ahk

; Idea: https://gist.github.com/davebrny/55de3ab40499e33e40324ac6a96b70c0

conditional_include(LibList) {

FileName := "~" . RegExReplace(A_ScriptName, "(.\w*$)") . "_includes.ahk"
file := FileOpen(FileName,"w") ; overwrite existing file
if !IsObject(file)
{
    MsgBox Can't open "%FileName%" for reading.
    return
} 

file.Write("; File generated by conditional_include()`r`n")

Loop Parse, LibList, CSV
{
    LibName := Trim(A_LoopField)
    If FileExist("Lib/" . LibName . ".ahk")  {
        file.Write("#include <" . LibName . ">`r`n") 
    }
}

file.Close()

} ; eofun
